export const MYCLASS_LIST_ACTION: string = 'MYCLASS_LIST_ACTION';
export const MODIFY_MYCLASS_LIST_ACTION: string = 'MODIFY_MYCLASS_LIST_ACTION';
export const POST_LIST_ACTION: string = 'POST_LIST_ACTION';
export const MAKE_CLASS: string = 'MAKE_CLASS';
export const MYCLASS_HOME: string = 'MYCLASS_HOME';
<<<<<<< HEAD
export const CLASS_MEMBER_INFO_ACTION: string = 'CLASS_MEMBER_INFO_ACTION';
export const MODIFY_CLASS_MEMBER_INFO: string = 'MODIFY_CLASS_MEMBER_INFO';
=======
export const UPDATE_SIDE_MENU_NUM_ACTION: string = 'UPDATE_SIDE_MENU_NUM_ACTION';
>>>>>>> 97d9e83904744d00c1f8d9412798797c19179f51
